name: anotacoes_de_atividades
description: Um aplicaitivo de anotações de atividades.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.0.3
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  path_provider: ^2.0.10
  sqflite: ^2.0.2+1
  sqflite_common_ffi: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  bloc_test: ^9.0.3
  test: ^1.21.1

flutter:
  uses-material-design: true
